# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(946, 774)
        MainWindow.setMinimumSize(QtCore.QSize(640, 580))
        MainWindow.setMaximumSize(QtCore.QSize(1180, 1000))
        MainWindow.setStyleSheet("QLabel{\n"
"    font: 16pt \"思源黑体 CN Normal\";\n"
"    color: #000;\n"
"}\n"
"QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame{\n"
"    border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame[card]{\n"
"    background-color: transparent;\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1, stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1, stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setProperty("card", True)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.srcImgLabel = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcImgLabel.sizePolicy().hasHeightForWidth())
        self.srcImgLabel.setSizePolicy(sizePolicy)
        self.srcImgLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.srcImgLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.srcImgLabel.setFont(font)
        self.srcImgLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.srcImgLabel.setText("")
        self.srcImgLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.srcImgLabel.setScaledContents(True)
        self.srcImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.srcImgLabel.setObjectName("srcImgLabel")
        self.gridLayout_2.addWidget(self.srcImgLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.channelRLabel = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelRLabel.sizePolicy().hasHeightForWidth())
        self.channelRLabel.setSizePolicy(sizePolicy)
        self.channelRLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.channelRLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.channelRLabel.setStyleSheet("QLabel{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.channelRLabel.setText("")
        self.channelRLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.channelRLabel.setScaledContents(True)
        self.channelRLabel.setObjectName("channelRLabel")
        self.gridLayout_8.addWidget(self.channelRLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setProperty("card", True)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.resultTableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.resultTableWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.resultTableWidget.setStyleSheet("/*QTableView 左上角样式*/\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: 5px solid rgba(241, 241, 241, 255);\n"
"    background-color:rgba(241, 241, 241, 255);\n"
" }\n"
"QTableWidget {\n"
"    font-size:12pt;\n"
"    color: rgb(81, 81, 81);/*表格内文字颜色*/\n"
"    gridline-color: #e4e4e4;/*表格内框颜色*/\n"
"    background-color: #fff; /*表格内背景色*/\n"
"}\n"
"QHeaderView {\n"
"    color:rgb(81, 81, 81);\n"
"    font: 75 14pt \"思源黑体 CN Bold\";\n"
"    background-color:rgba(241, 241, 241, 255);\n"
"    min-height:40px;\n"
"}\n"
"QHeaderView::section {\n"
"    color:rgb(81, 81, 81);\n"
"    background-color: qlineargradient(spread:pad, x1:0.692, y1:0.926136,x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,182, 255));\n"
"    border: 1px solid #e4e4e4;\n"
"}")
        self.resultTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(2)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        self.resultTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.resultTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.resultTableWidget.verticalHeader().setVisible(False)
        self.resultTableWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_5.addWidget(self.resultTableWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("\n"
"QPushButton{\n"
"    max-height:60px;\n"
"    min-height:60px;\n"
"    min-width:100px;\n"
"    max-width:100px;\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: #fff;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:rgba(64, 158, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:rgba(217, 221, 230, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setProperty("card", True)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 4, 1, 1)
        self.mClearBtn = QtWidgets.QPushButton(self.frame_2)
        self.mClearBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.mClearBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.mClearBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mClearBtn.setObjectName("mClearBtn")
        self.gridLayout_3.addWidget(self.mClearBtn, 0, 7, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 8, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.measureBtn = QtWidgets.QPushButton(self.frame_2)
        self.measureBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.measureBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.measureBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.measureBtn.setObjectName("measureBtn")
        self.gridLayout_3.addWidget(self.measureBtn, 0, 5, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 2, 1, 1)
        self.captureImgBtn = QtWidgets.QPushButton(self.frame_2)
        self.captureImgBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.captureImgBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.captureImgBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.captureImgBtn.setObjectName("captureImgBtn")
        self.gridLayout_3.addWidget(self.captureImgBtn, 0, 6, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_3.addWidget(self.pushButton_3, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "L(a.u)"))
        self.pushButton_2.setText(_translate("MainWindow", "滴定"))
        self.mClearBtn.setText(_translate("MainWindow", "清空"))
        self.measureBtn.setText(_translate("MainWindow", "检测"))
        self.pushButton.setText(_translate("MainWindow", "上液"))
        self.captureImgBtn.setText(_translate("MainWindow", "抓图"))
        self.pushButton_3.setText(_translate("MainWindow", "倒流"))
import images_rc
