# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
#import motor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1180,1000)
        MainWindow.setMinimumSize(QtCore.QSize(1180,1000))
        MainWindow.setMaximumSize(QtCore.QSize(1180,1000))
        MainWindow.setStyleSheet("QLabel{\n"
"    font: 16pt \"思源黑体 CN Normal\";\n"
"    color: #000;\n"
"}\n"
"QWidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame{\n"
"    border:none;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QFrame[card]{\n"
"    background-color: transparent;\n"
"    border-top: 10px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 10px solid qlineargradient(x0:0, x1:1, stop: 0 #ececef, stop: 1 white);\n"
"    border-bottom: 10px solid qlineargradient(y0:0, y1:1, stop: 0 white, stop: 1  #ececef);\n"
"    border-right: 10px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 #ececef);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setProperty("card", True)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_7.setContentsMargins(10, 0, 10, 0)
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setMinimumSize(QtCore.QSize(0, 50))
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setStyleSheet("border:none;")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.cameraListComboBox = QtWidgets.QComboBox(self.frame_4)
        self.cameraListComboBox.setMinimumSize(QtCore.QSize(0, 50))
        self.cameraListComboBox.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cameraListComboBox.setFont(font)
        self.cameraListComboBox.setObjectName("cameraListComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.cameraListComboBox)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_4, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setStyleSheet("#frame_6{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.srcImgLabel = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcImgLabel.sizePolicy().hasHeightForWidth())
        self.srcImgLabel.setSizePolicy(sizePolicy)
        self.srcImgLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.srcImgLabel.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.srcImgLabel.setFont(font)
        self.srcImgLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.srcImgLabel.setText("")
        self.srcImgLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.srcImgLabel.setScaledContents(True)
        self.srcImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.srcImgLabel.setObjectName("srcImgLabel")
        self.gridLayout_2.addWidget(self.srcImgLabel, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.channelRLabel = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelRLabel.sizePolicy().hasHeightForWidth())
        self.channelRLabel.setSizePolicy(sizePolicy)
        self.channelRLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.channelRLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.channelRLabel.setStyleSheet("QLabel{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.channelRLabel.setText("")
        self.channelRLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.channelRLabel.setScaledContents(True)
        self.channelRLabel.setObjectName("channelRLabel")
        self.gridLayout_8.addWidget(self.channelRLabel, 0, 0, 1, 1)
        self.channelGLabel = QtWidgets.QLabel(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelGLabel.sizePolicy().hasHeightForWidth())
        self.channelGLabel.setSizePolicy(sizePolicy)
        self.channelGLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.channelGLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.channelGLabel.setStyleSheet("QLabel{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.channelGLabel.setText("")
        self.channelGLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.channelGLabel.setScaledContents(True)
        self.channelGLabel.setObjectName("channelGLabel")
        self.gridLayout_8.addWidget(self.channelGLabel, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.frame_7, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setProperty("card", True)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 300))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_9.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_9.setSpacing(10)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.exposureSlider = QtWidgets.QSlider(self.frame_8)
        self.exposureSlider.setMinimum(-8)
        self.exposureSlider.setMaximum(0)
        self.exposureSlider.setOrientation(QtCore.Qt.Horizontal)
        self.exposureSlider.setObjectName("exposureSlider")
        self.horizontalLayout.addWidget(self.exposureSlider)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.x0Slider = QtWidgets.QSlider(self.frame_8)
        self.x0Slider.setMinimum(0)
        self.x0Slider.setMaximum(1600)
        #self.x0Slider.setMaximum(640)
        self.x0Slider.setOrientation(QtCore.Qt.Horizontal)
        self.x0Slider.setObjectName("x0Slider")
        self.horizontalLayout_2.addWidget(self.x0Slider)
        self.x0Label = QtWidgets.QLabel(self.frame_8)
        self.x0Label.setMinimumSize(QtCore.QSize(60, 0))
        self.x0Label.setObjectName("x0Label")
        self.horizontalLayout_2.addWidget(self.x0Label)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_8)
        self.label_6.setMinimumSize(QtCore.QSize(60, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.y0Slider = QtWidgets.QSlider(self.frame_8)
        self.y0Slider.setMinimum(0)
        self.y0Slider.setMaximum(1200)
        #self.y0Slider.setMaximum(480)
        self.y0Slider.setOrientation(QtCore.Qt.Horizontal)
        self.y0Slider.setObjectName("y0Slider")
        self.horizontalLayout_3.addWidget(self.y0Slider)
        self.y0Label = QtWidgets.QLabel(self.frame_8)
        self.y0Label.setMinimumSize(QtCore.QSize(60, 0))
        self.y0Label.setObjectName("y0Label")
        self.horizontalLayout_3.addWidget(self.y0Label)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.x1Slider = QtWidgets.QSlider(self.frame_8)
        self.x1Slider.setMinimum(0)
        self.x1Slider.setMaximum(1600)
        #self.x1Slider.setMaximum(640)
        self.x1Slider.setOrientation(QtCore.Qt.Horizontal)
        self.x1Slider.setObjectName("x1Slider")
        self.horizontalLayout_4.addWidget(self.x1Slider)
        self.x1Label = QtWidgets.QLabel(self.frame_8)
        self.x1Label.setMinimumSize(QtCore.QSize(60, 0))
        self.x1Label.setObjectName("x1Label")
        self.horizontalLayout_4.addWidget(self.x1Label)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 3, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_10 = QtWidgets.QLabel(self.frame_8)
        self.label_10.setMinimumSize(QtCore.QSize(60, 0))
        self.label_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_5.addWidget(self.label_10)
        self.y1Slider = QtWidgets.QSlider(self.frame_8)
        self.y1Slider.setMinimum(0)
        self.y1Slider.setMaximum(1200)
        #self.y1Slider.setMaximum(480)
        self.y1Slider.setOrientation(QtCore.Qt.Horizontal)
        self.y1Slider.setObjectName("y1Slider")
        self.horizontalLayout_5.addWidget(self.y1Slider)
        self.y1Label = QtWidgets.QLabel(self.frame_8)
        self.y1Label.setMinimumSize(QtCore.QSize(60, 0))
        self.y1Label.setObjectName("y1Label")
        self.horizontalLayout_5.addWidget(self.y1Label)
        self.gridLayout_9.addLayout(self.horizontalLayout_5, 4, 0, 1, 2)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.frame_8)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.widthLabel = QtWidgets.QLabel(self.frame_8)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.widthLabel)
        self.gridLayout_9.addLayout(self.formLayout_2, 5, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_8)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.heightLabel = QtWidgets.QLabel(self.frame_8)
        self.heightLabel.setObjectName("heightLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.heightLabel)
        self.gridLayout_9.addLayout(self.formLayout_3, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame_8, 0, 0, 1, 1)
        self.resultTableWidget = QtWidgets.QTableWidget(self.frame_3)
        self.resultTableWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.resultTableWidget.setStyleSheet("/*QTableView 左上角样式*/\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: 5px solid rgba(241, 241, 241, 255);\n"
"    background-color:rgba(241, 241, 241, 255);\n"
" }\n"
"QTableWidget {\n"
"    font-size:12pt;\n"
"    color: rgb(81, 81, 81);/*表格内文字颜色*/\n"
"    gridline-color: #e4e4e4;/*表格内框颜色*/\n"
"    background-color: #fff; /*表格内背景色*/\n"
"}\n"
"QHeaderView {\n"
"    color:rgb(81, 81, 81);\n"
"    font: 75 14pt \"思源黑体 CN Bold\";\n"
"    background-color:rgba(241, 241, 241, 255);\n"
"    min-height:40px;\n"
"}\n"
"QHeaderView::section {\n"
"    color:rgb(81, 81, 81);\n"
"    background-color: qlineargradient(spread:pad, x1:0.692, y1:0.926136,x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,182, 255));\n"
"    border: 1px solid #e4e4e4;\n"
"}")
        self.resultTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(3)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(2, item)
        self.resultTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.resultTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.resultTableWidget.verticalHeader().setVisible(False)
        self.resultTableWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_5.addWidget(self.resultTableWidget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 0, 1, 2, 1)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_2.setStyleSheet("\n"
"QPushButton{\n"
"    max-height:60px;\n"
"    min-height:60px;\n"
"    min-width:100px;\n"
"    max-width:100px;\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: #fff;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:rgba(64, 158, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255);\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color:rgba(217, 221, 230, 255);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setProperty("card", True)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_3.setSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.captureImgBtn = QtWidgets.QPushButton(self.frame_2)
        self.captureImgBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.captureImgBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.captureImgBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.captureImgBtn.setObjectName("captureImgBtn")
        self.gridLayout_3.addWidget(self.captureImgBtn, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 5, 1, 1)
        
        self.measureBtn = QtWidgets.QPushButton(self.frame_2)
        self.measureBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.measureBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.measureBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.measureBtn.setObjectName("measureBtn")
        self.gridLayout_3.addWidget(self.measureBtn, 0, 3, 1, 1)
        
        self.mClearBtn = QtWidgets.QPushButton(self.frame_2)
        self.mClearBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.mClearBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.mClearBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mClearBtn.setObjectName("mClearBtn")
        self.gridLayout_3.addWidget(self.mClearBtn, 0, 4, 1, 1)
        
        #self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        
        self.titrationBtn = QtWidgets.QPushButton(self.frame_2)
        self.titrationBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.titrationBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.titrationBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.titrationBtn.setObjectName("titrationBtn")
        self.gridLayout_3.addWidget(self.titrationBtn, 0, 5, 1, 1)
        #self.titrationBtn.clicked.connect(motor.titration)
        
        
        self.fillBtn = QtWidgets.QPushButton(self.frame_2)
        self.fillBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.fillBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.fillBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fillBtn.setObjectName("fillBtn")
        self.gridLayout_3.addWidget(self.fillBtn, 0, 1, 1, 1)
        #self.fillBtn.clicked.connect(motor.fill)
        
        
        self.drainageBtn = QtWidgets.QPushButton(self.frame_2)
        self.drainageBtn.setMinimumSize(QtCore.QSize(100, 60))
        self.drainageBtn.setMaximumSize(QtCore.QSize(100, 60))
        self.drainageBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drainageBtn.setObjectName("fillBtn")
        self.gridLayout_3.addWidget(self.drainageBtn, 0, 0, 1, 1)
        #self.drainageBtn.clicked.connect(motor.drainage)
        
        
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.exposureSlider.valueChanged['int'].connect(self.label_3.setNum)
        self.x0Slider.valueChanged['int'].connect(self.x0Label.setNum)
        self.y0Slider.valueChanged['int'].connect(self.y0Label.setNum)
        self.y1Slider.valueChanged['int'].connect(self.y1Label.setNum)
        self.x1Slider.valueChanged['int'].connect(self.x1Label.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "选择相机:"))
        self.label_2.setText(_translate("MainWindow", "亮度:"))
        self.label_3.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "x0:"))
        self.x0Label.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "y0:"))
        self.y0Label.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "x1:"))
        self.x1Label.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "y1:"))
        self.y1Label.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "宽度:"))
        self.widthLabel.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "高度:"))
        self.heightLabel.setText(_translate("MainWindow", "0"))
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R(a.u)"))
        item = self.resultTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "G(a.u)"))
        self.captureImgBtn.setText(_translate("MainWindow", "抓图"))
        self.measureBtn.setText(_translate("MainWindow", "检测"))
        self.mClearBtn.setText(_translate("MainWindow", "清空"))
        self.titrationBtn.setText(_translate("MainWindow", "滴定"))
        self.fillBtn.setText(_translate("MainWindow", "Fill"))
        self.drainageBtn.setText(_translate("MainWindow", "排水"))
        
import images_rc
