# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyboardDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyboardDialog(object):
    def setupUi(self, KeyboardDialog):
        KeyboardDialog.setObjectName("KeyboardDialog")
        KeyboardDialog.resize(480, 310)
        KeyboardDialog.setMinimumSize(QtCore.QSize(480, 300))
        KeyboardDialog.setMaximumSize(QtCore.QSize(480, 310))
        KeyboardDialog.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(KeyboardDialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(KeyboardDialog)
        self.frame.setStyleSheet("QFrame{\n"
"    border: none;\n"
"    background-color: rgb(235, 235, 235);\n"
"    border-left-color: rgb(85, 0, 0);\n"
"    border-radius: 20px 20px 0px 0px;\n"
"    border-left: 10px solid qlineargradient(spread:pad, x1:1, y1:0.267, x2:0, y2:0.256, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(245, 245, 245, 255));\n"
"    border-right: 10px solid qlineargradient(spread:pad, x1:0, y1:0.574, x2:1, y2:0.563, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(245, 245, 245, 255));\n"
"}\n"
"QPushButton{\n"
"    min-width:80px;\n"
"    max-width:80px;\n"
"    min-height:60px;\n"
"    max-height:60px;\n"
"    outline:none;\n"
"    border: none;\n"
"    border-radius:10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"    font: 57 14pt \"思源黑体 CN Medium\";\n"
"    color: rgb(111, 111, 111);\n"
"}\n"
"QPushButton::pressed{\n"
"    background-color: rgb(214, 214, 214);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.pushButton_1 = QtWidgets.QPushButton(self.frame)
        self.pushButton_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_2.addWidget(self.pushButton_1, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 2, 1, 2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 4, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.frame)
        self.pushButton_25.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 1, 5, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(87, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 0, 2, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 2, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 4, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame)
        self.pushButton_26.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_2.addWidget(self.pushButton_26, 2, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(86, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 2, 6, 2, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 3, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_2.addWidget(self.pushButton_8, 3, 2, 1, 2)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_2.addWidget(self.pushButton_9, 3, 4, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame)
        self.pushButton_27.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_2.addWidget(self.pushButton_27, 3, 5, 1, 1)
        self.pushButton_0 = QtWidgets.QPushButton(self.frame)
        self.pushButton_0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_0.setObjectName("pushButton_0")
        self.gridLayout_2.addWidget(self.pushButton_0, 4, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_2.addWidget(self.pushButton_10, 4, 2, 1, 2)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_2.addWidget(self.pushButton_11, 4, 4, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_2.addWidget(self.pushButton_12, 4, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 5, 3, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.retranslateUi(KeyboardDialog)
        QtCore.QMetaObject.connectSlotsByName(KeyboardDialog)

    def retranslateUi(self, KeyboardDialog):
        _translate = QtCore.QCoreApplication.translate
        KeyboardDialog.setWindowTitle(_translate("KeyboardDialog", "Dialog"))
        self.pushButton_1.setText(_translate("KeyboardDialog", "1"))
        self.pushButton_2.setText(_translate("KeyboardDialog", "2"))
        self.pushButton_3.setText(_translate("KeyboardDialog", "3"))
        self.pushButton_25.setText(_translate("KeyboardDialog", "←"))
        self.pushButton_4.setText(_translate("KeyboardDialog", "4"))
        self.pushButton_5.setText(_translate("KeyboardDialog", "5"))
        self.pushButton_6.setText(_translate("KeyboardDialog", "6"))
        self.pushButton_26.setText(_translate("KeyboardDialog", "*"))
        self.pushButton_7.setText(_translate("KeyboardDialog", "7"))
        self.pushButton_8.setText(_translate("KeyboardDialog", "8"))
        self.pushButton_9.setText(_translate("KeyboardDialog", "9"))
        self.pushButton_27.setText(_translate("KeyboardDialog", "#"))
        self.pushButton_0.setText(_translate("KeyboardDialog", "0"))
        self.pushButton_10.setText(_translate("KeyboardDialog", "."))
        self.pushButton_11.setText(_translate("KeyboardDialog", "清空"))
        self.pushButton_12.setText(_translate("KeyboardDialog", "确定"))
