# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageBox(object):
    def setupUi(self, MessageBox):
        MessageBox.setObjectName("MessageBox")
        MessageBox.resize(280, 362)
        MessageBox.setMinimumSize(QtCore.QSize(280, 0))
        MessageBox.setMaximumSize(QtCore.QSize(280, 500))
        MessageBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MessageBox.setStyleSheet("background-color: #f2f2f2;")
        self.gridLayout_2 = QtWidgets.QGridLayout(MessageBox)
        self.gridLayout_2.setContentsMargins(0, 30, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(5)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(MessageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 120))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(10, 0, 10, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.logoLabel = QtWidgets.QLabel(self.frame)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap(":/images/info.svg"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.gridLayout.addWidget(self.logoLabel, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(MessageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.titleLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Bold")
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_3.addWidget(self.titleLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(MessageBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Medium")
        font.setPointSize(12)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setContentsMargins(20, 0, 20, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.msgLabel = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msgLabel.sizePolicy().hasHeightForWidth())
        self.msgLabel.setSizePolicy(sizePolicy)
        self.msgLabel.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Normal")
        font.setPointSize(14)
        self.msgLabel.setFont(font)
        self.msgLabel.setTextFormat(QtCore.Qt.AutoText)
        self.msgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.msgLabel.setWordWrap(True)
        self.msgLabel.setIndent(0)
        self.msgLabel.setObjectName("msgLabel")
        self.gridLayout_4.addWidget(self.msgLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_3, 2, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(MessageBox)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(20)
        self.gridLayout_5.setVerticalSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 0, 1, 1)
        self.acceptBtn = QtWidgets.QPushButton(self.frame_4)
        self.acceptBtn.setMinimumSize(QtCore.QSize(100, 50))
        self.acceptBtn.setMaximumSize(QtCore.QSize(100, 50))
        self.acceptBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acceptBtn.setFocusPolicy(QtCore.Qt.TabFocus)
        self.acceptBtn.setStyleSheet("QPushButton{\n"
"    font: 87 14pt \"思源黑体 CN Heavy\";\n"
"    color: rgb(255, 255, 255);\n"
"    border:none;\n"
"    outline:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(103, 194, 58, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(245, 108, 108, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}")
        self.acceptBtn.setObjectName("acceptBtn")
        self.gridLayout_5.addWidget(self.acceptBtn, 0, 1, 1, 1)
        self.rejectBtn = QtWidgets.QPushButton(self.frame_4)
        self.rejectBtn.setMinimumSize(QtCore.QSize(100, 50))
        self.rejectBtn.setMaximumSize(QtCore.QSize(100, 50))
        self.rejectBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rejectBtn.setStyleSheet("QPushButton{\n"
"    font: 87 14pt \"思源黑体 CN Heavy\";\n"
"    color: #fff;\n"
"    border:none;\n"
"    outline:none;\n"
"    border-radius:5px;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(245, 108, 108, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}")
        self.rejectBtn.setObjectName("rejectBtn")
        self.gridLayout_5.addWidget(self.rejectBtn, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.frame_4, 3, 0, 1, 1)

        self.retranslateUi(MessageBox)
        self.acceptBtn.clicked.connect(MessageBox.accept)
        self.rejectBtn.clicked.connect(MessageBox.reject)
        QtCore.QMetaObject.connectSlotsByName(MessageBox)

    def retranslateUi(self, MessageBox):
        _translate = QtCore.QCoreApplication.translate
        MessageBox.setWindowTitle(_translate("MessageBox", "Dialog"))
        self.titleLabel.setText(_translate("MessageBox", "标题"))
        self.msgLabel.setText(_translate("MessageBox", "消息"))
        self.acceptBtn.setText(_translate("MessageBox", "确定"))
        self.rejectBtn.setText(_translate("MessageBox", "取消"))
import images_rc
