# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        MainWindow.setMaximumSize(QtCore.QSize(800, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton, label{\n"
"    color: rgb(81, 81, 81);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.stackedWidget.setObjectName("stackedWidget")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.homePage)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.homePage)
        self.frame_4.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setHorizontalSpacing(0)
        self.gridLayout_11.setVerticalSpacing(20)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 106, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 270))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 270))
        self.frame_3.setStyleSheet("QPushButton{\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"    border:none;\n"
"    outline:none;\n"
"    border-radius:5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.queryBtn = QtWidgets.QPushButton(self.frame_3)
        self.queryBtn.setGeometry(QtCore.QRect(340, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryBtn.sizePolicy().hasHeightForWidth())
        self.queryBtn.setSizePolicy(sizePolicy)
        self.queryBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.queryBtn.setStyleSheet("QPushButton{\n"
"\n"
"    background-color:#00aa7f;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.queryBtn.setObjectName("queryBtn")
        self.testBtn = QtWidgets.QPushButton(self.frame_3)
        self.testBtn.setGeometry(QtCore.QRect(200, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testBtn.sizePolicy().hasHeightForWidth())
        self.testBtn.setSizePolicy(sizePolicy)
        self.testBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.testBtn.setStyleSheet("QPushButton{\n"
"    background-color:#0000ff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.testBtn.setObjectName("testBtn")
        self.shutdownBtn = QtWidgets.QPushButton(self.frame_3)
        self.shutdownBtn.setGeometry(QtCore.QRect(480, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutdownBtn.sizePolicy().hasHeightForWidth())
        self.shutdownBtn.setSizePolicy(sizePolicy)
        self.shutdownBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shutdownBtn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    outline:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#ff007f;\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.shutdownBtn.setIconSize(QtCore.QSize(60, 60))
        self.shutdownBtn.setObjectName("shutdownBtn")
        self.tempBtn = QtWidgets.QPushButton(self.frame_3)
        self.tempBtn.setGeometry(QtCore.QRect(340, 140, 120, 120))
        self.tempBtn.setMinimumSize(QtCore.QSize(120, 120))
        self.tempBtn.setMaximumSize(QtCore.QSize(120, 120))
        self.tempBtn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    outline:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#ff0000;\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 150, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(180, 130, 76, 255)\n"
"}")
        self.tempBtn.setObjectName("tempBtn")
        self.quitBtn = QtWidgets.QPushButton(self.frame_3)
        self.quitBtn.setGeometry(QtCore.QRect(200, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitBtn.sizePolicy().hasHeightForWidth())
        self.quitBtn.setSizePolicy(sizePolicy)
        self.quitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.quitBtn.setStyleSheet("QPushButton{\n"
"    background-color:#00aa00;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.quitBtn.setObjectName("quitBtn")
        self.tempBtn_2 = QtWidgets.QPushButton(self.frame_3)
        self.tempBtn_2.setGeometry(QtCore.QRect(480, 10, 120, 120))
        self.tempBtn_2.setMinimumSize(QtCore.QSize(120, 120))
        self.tempBtn_2.setMaximumSize(QtCore.QSize(120, 120))
        self.tempBtn_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    outline:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#ff0000;\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 150, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(180, 130, 76, 255)\n"
"}")
        self.tempBtn_2.setObjectName("tempBtn_2")
        self.gridLayout_11.addWidget(self.frame_3, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.homePage)
        self.tempPage = QtWidgets.QWidget()
        self.tempPage.setObjectName("tempPage")
        self.frame_5 = QtWidgets.QFrame(self.tempPage)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.frame_5.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.temp = QtWidgets.QLineEdit(self.frame_5)
        self.temp.setGeometry(QtCore.QRect(160, 70, 500, 100))
        self.temp.setMinimumSize(QtCore.QSize(80, 100))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(20)
        self.temp.setFont(font)
        self.temp.setCursor(QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.temp.setStyleSheet("QPushButton{\n"
"    background-color:#409EFF;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 0, 255, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 255, 255, 255)\n"
"}")
        self.temp.setObjectName("temp")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(11, 199, 778, 270))
        self.frame_6.setMinimumSize(QtCore.QSize(0, 270))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 270))
        self.frame_6.setStyleSheet("QPushButton{\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"    border:none;\n"
"    outline:none;\n"
"    border-radius:5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.temp_downBtn_2 = QtWidgets.QPushButton(self.frame_6)
        self.temp_downBtn_2.setGeometry(QtCore.QRect(340, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_downBtn_2.sizePolicy().hasHeightForWidth())
        self.temp_downBtn_2.setSizePolicy(sizePolicy)
        self.temp_downBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.temp_downBtn_2.setStyleSheet("QPushButton{\n"
"    background-color:#00007f;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.temp_downBtn_2.setObjectName("temp_downBtn_2")
        self.temp_upBtn = QtWidgets.QPushButton(self.frame_6)
        self.temp_upBtn.setGeometry(QtCore.QRect(490, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_upBtn.sizePolicy().hasHeightForWidth())
        self.temp_upBtn.setSizePolicy(sizePolicy)
        self.temp_upBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.temp_upBtn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    outline:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#aa0000;\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.temp_upBtn.setIconSize(QtCore.QSize(60, 60))
        self.temp_upBtn.setObjectName("temp_upBtn")
        self.backBtn_2 = QtWidgets.QPushButton(self.frame_6)
        self.backBtn_2.setGeometry(QtCore.QRect(20, 140, 120, 120))
        self.backBtn_2.setMinimumSize(QtCore.QSize(120, 120))
        self.backBtn_2.setMaximumSize(QtCore.QSize(120, 120))
        self.backBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn_2.setStyleSheet("QPushButton{\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: #909399;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(150, 243, 150, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(144, 147, 153, 255), stop:1 rgba(94, 94, 94, 255));\n"
"}")
        self.backBtn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn_2.setIcon(icon)
        self.backBtn_2.setIconSize(QtCore.QSize(48, 48))
        self.backBtn_2.setObjectName("backBtn_2")
        self.temp_downBtn = QtWidgets.QPushButton(self.frame_6)
        self.temp_downBtn.setGeometry(QtCore.QRect(180, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_downBtn.sizePolicy().hasHeightForWidth())
        self.temp_downBtn.setSizePolicy(sizePolicy)
        self.temp_downBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.temp_downBtn.setStyleSheet("QPushButton{\n"
"    background-color:#55007f;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.temp_downBtn.setObjectName("temp_downBtn")
        self.stopBtn = QtWidgets.QPushButton(self.frame_6)
        self.stopBtn.setGeometry(QtCore.QRect(640, 140, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopBtn.sizePolicy().hasHeightForWidth())
        self.stopBtn.setSizePolicy(sizePolicy)
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopBtn.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    outline:none;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color:#ff007f;\n"
"    min-width:120px;\n"
"    max-width:120px;\n"
"    min-height:120px;\n"
"    max-height:120px;\n"
"    font: 57 24pt \"思源黑体 CN Medium\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.stopBtn.setIconSize(QtCore.QSize(60, 60))
        self.stopBtn.setObjectName("stopBtn")
        self.ding_halfBtn = QtWidgets.QPushButton(self.frame_6)
        self.ding_halfBtn.setGeometry(QtCore.QRect(180, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ding_halfBtn.sizePolicy().hasHeightForWidth())
        self.ding_halfBtn.setSizePolicy(sizePolicy)
        self.ding_halfBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ding_halfBtn.setStyleSheet("QPushButton{\n"
"    background-color:#05a8ff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.ding_halfBtn.setObjectName("ding_halfBtn")
        self.ding_halfBtn_2 = QtWidgets.QPushButton(self.frame_6)
        self.ding_halfBtn_2.setGeometry(QtCore.QRect(340, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ding_halfBtn_2.sizePolicy().hasHeightForWidth())
        self.ding_halfBtn_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Medium")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.ding_halfBtn_2.setFont(font)
        self.ding_halfBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ding_halfBtn_2.setStyleSheet("QPushButton{\n"
"    background-color:#365d56;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.ding_halfBtn_2.setObjectName("ding_halfBtn_2")
        self.testBtn_2 = QtWidgets.QPushButton(self.frame_6)
        self.testBtn_2.setGeometry(QtCore.QRect(490, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.testBtn_2.sizePolicy().hasHeightForWidth())
        self.testBtn_2.setSizePolicy(sizePolicy)
        self.testBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.testBtn_2.setStyleSheet("QPushButton{\n"
"    background-color:#0000ff;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(255, 135, 76, 255)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgba(255, 76, 76, 255)\n"
"}")
        self.testBtn_2.setObjectName("testBtn_2")
        self.stackedWidget.addWidget(self.tempPage)
        self.testPage = QtWidgets.QWidget()
        self.testPage.setObjectName("testPage")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.testPage)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_8 = QtWidgets.QFrame(self.testPage)
        self.frame_8.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_8.setContentsMargins(5, 0, 5, 0)
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setVerticalSpacing(5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setStyleSheet("QPushButton{\n"
"font: 87 16pt \"思源黑体 CN Heavy\";\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.frame = QtWidgets.QFrame(self.frame_10)
        self.frame.setGeometry(QtCore.QRect(0, 380, 791, 91))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setStyleSheet("QPushButton{\n"
"    max-height:80px;\n"
"    min-height:80px;\n"
"    min-width:80px;\n"
"    max-width:80px;\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: rgb(81, 81, 81);\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(243, 243, 243, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(144, 147, 153, 255), stop:1 rgba(94, 94, 94, 255));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.backBtn = QtWidgets.QPushButton(self.frame)
        self.backBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.backBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.backBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backBtn.setStyleSheet("QPushButton{\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: #909399;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(243, 243, 243, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(144, 147, 153, 255), stop:1 rgba(94, 94, 94, 255));\n"
"}")
        self.backBtn.setText("")
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(48, 48))
        self.backBtn.setObjectName("backBtn")
        self.gridLayout_2.addWidget(self.backBtn, 0, 0, 1, 1)
        self.captureImgBtn = QtWidgets.QPushButton(self.frame)
        self.captureImgBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.captureImgBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.captureImgBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.captureImgBtn.setStyleSheet("")
        self.captureImgBtn.setObjectName("captureImgBtn")
        self.gridLayout_2.addWidget(self.captureImgBtn, 0, 2, 1, 1)
        self.measureBtn = QtWidgets.QPushButton(self.frame)
        self.measureBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.measureBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.measureBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.measureBtn.setObjectName("measureBtn")
        self.gridLayout_2.addWidget(self.measureBtn, 0, 6, 1, 1)
        self.previewBtn = QtWidgets.QPushButton(self.frame)
        self.previewBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.previewBtn.setMaximumSize(QtCore.QSize(80, 80))
        self.previewBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.previewBtn.setObjectName("previewBtn")
        self.gridLayout_2.addWidget(self.previewBtn, 0, 3, 1, 1)
        self.lamp_Btn = QtWidgets.QPushButton(self.frame)
        self.lamp_Btn.setMinimumSize(QtCore.QSize(80, 80))
        self.lamp_Btn.setMaximumSize(QtCore.QSize(80, 80))
        self.lamp_Btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lamp_Btn.setObjectName("lamp_Btn")
        self.gridLayout_2.addWidget(self.lamp_Btn, 0, 1, 1, 1)
        self.mClearBtn = QtWidgets.QPushButton(self.frame)
        self.mClearBtn.setMinimumSize(QtCore.QSize(80, 80))
        self.mClearBtn.setMaximumSize(QtCore.QSize(80, 80))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN Heavy")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.mClearBtn.setFont(font)
        self.mClearBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mClearBtn.setObjectName("mClearBtn")
        self.gridLayout_2.addWidget(self.mClearBtn, 0, 7, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 490, 380))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 380))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 390))
        self.frame_12.setStyleSheet("QLabel{\n"
"border: 3px solid;\n"
"border-top-color: qlineargradient(spread:pad, x1:0.522, y1:1, x2:0.487627, y2:0, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-bottom-color: qlineargradient(spread:pad, x1:0.477, y1:0, x2:0.488, y2:1, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-left-color: qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.517, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-right-color: qlineargradient(spread:pad, x1:0, y1:0.528, x2:1, y2:0.539727, stop:0 rgba(133, 133, 133, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_9 = QtWidgets.QFrame(self.frame_12)
        self.frame_9.setGeometry(QtCore.QRect(10, 10, 470, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.numLineEdit = QtWidgets.QLineEdit(self.frame_9)
        self.numLineEdit.setMinimumSize(QtCore.QSize(360, 50))
        self.numLineEdit.setMaximumSize(QtCore.QSize(360, 50))
        self.numLineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.numLineEdit.setStyleSheet("QLineEdit{\n"
"    color: rgb(75, 75, 75);\n"
"    font: 57 14pt \"思源黑体 CN Medium\";\n"
"    border:1px solid #e4e4e4;\n"
"    border-radius:20px;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    \n"
"    background-color: rgba(64, 158, 255, 50);\n"
"}\n"
"")
        self.numLineEdit.setText("")
        self.numLineEdit.setMaxLength(30)
        self.numLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.numLineEdit.setDragEnabled(False)
        self.numLineEdit.setClearButtonEnabled(False)
        self.numLineEdit.setObjectName("numLineEdit")
        self.gridLayout_20.addWidget(self.numLineEdit, 0, 0, 1, 1)
        self.srcImgLabel = QtWidgets.QLabel(self.frame_12)
        self.srcImgLabel.setGeometry(QtCore.QRect(10, 100, 470, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.srcImgLabel.sizePolicy().hasHeightForWidth())
        self.srcImgLabel.setSizePolicy(sizePolicy)
        self.srcImgLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.srcImgLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.srcImgLabel.setFont(font)
        self.srcImgLabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.srcImgLabel.setText("")
        self.srcImgLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.srcImgLabel.setScaledContents(True)
        self.srcImgLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.srcImgLabel.setObjectName("srcImgLabel")
        self.channelRLabel = QtWidgets.QLabel(self.frame_12)
        self.channelRLabel.setGeometry(QtCore.QRect(10, 230, 470, 130))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelRLabel.sizePolicy().hasHeightForWidth())
        self.channelRLabel.setSizePolicy(sizePolicy)
        self.channelRLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.channelRLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.channelRLabel.setText("")
        self.channelRLabel.setPixmap(QtGui.QPixmap(":/images/logo2.png"))
        self.channelRLabel.setScaledContents(True)
        self.channelRLabel.setObjectName("channelRLabel")
        self.resultTableWidget = QtWidgets.QTableWidget(self.frame_10)
        self.resultTableWidget.setGeometry(QtCore.QRect(490, 10, 291, 241))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.resultTableWidget.setFont(font)
        self.resultTableWidget.setStyleSheet("/*QTableView 左上角样式*/\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: 5px solid rgba(241, 241, 241, 255);\n"
"    background-color:rgba(241, 241, 241, 255);\n"
" }\n"
"QTableWidget {\n"
"    font-size:12pt;\n"
"    color: rgb(81, 81, 81);/*表格内文字颜色*/\n"
"    gridline-color: #e4e4e4;/*表格内框颜色*/\n"
"    background-color: #fff; /*表格内背景色*/\n"
"}\n"
"QHeaderView {\n"
"    color:rgb(81, 81, 81);\n"
"    font: 75 14pt \"思源黑体 CN Bold\";\n"
"    background-color:rgba(241, 241, 241, 255);\n"
"    min-height:40px;\n"
"}\n"
"QHeaderView::section {\n"
"    color:rgb(81, 81, 81);\n"
"    background-color: qlineargradient(spread:pad, x1:0.692, y1:0.926136,x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,182, 255));\n"
"    border: 1px solid #e4e4e4;\n"
"}")
        self.resultTableWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.resultTableWidget.setObjectName("resultTableWidget")
        self.resultTableWidget.setColumnCount(2)
        self.resultTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.resultTableWidget.setHorizontalHeaderItem(1, item)
        self.resultTableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.resultTableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.resultTableWidget.horizontalHeader().setStretchLastSection(True)
        self.resultTableWidget.verticalHeader().setVisible(False)
        self.resultTableWidget.verticalHeader().setHighlightSections(False)
        self.lamp_2 = QtWidgets.QLabel(self.frame_10)
        self.lamp_2.setGeometry(QtCore.QRect(500, 310, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lamp_2.setFont(font)
        self.lamp_2.setStyleSheet("border: 1px solid black;")
        self.lamp_2.setText("")
        self.lamp_2.setObjectName("lamp_2")
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setGeometry(QtCore.QRect(500, 260, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe 黑体 Std R")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 1px solid black;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.frame_10, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.frame_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.testPage)
        self.queryPage = QtWidgets.QWidget()
        self.queryPage.setObjectName("queryPage")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.queryPage)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_7 = QtWidgets.QFrame(self.queryPage)
        self.frame_7.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_19.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_19.setHorizontalSpacing(0)
        self.gridLayout_19.setVerticalSpacing(10)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.frame_14 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_14.sizePolicy().hasHeightForWidth())
        self.frame_14.setSizePolicy(sizePolicy)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_22.setContentsMargins(10, 10, 10, 0)
        self.gridLayout_22.setHorizontalSpacing(10)
        self.gridLayout_22.setVerticalSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_17.sizePolicy().hasHeightForWidth())
        self.frame_17.setSizePolicy(sizePolicy)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_17.setStyleSheet("QLabel,QDateEdit,QComboBox{\n"
"    font: 57 16pt \"思源黑体 CN Medium\";\n"
"    height: 50px;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.layoutWidget = QtWidgets.QWidget(self.frame_17)
        self.layoutWidget.setGeometry(QtCore.QRect(1, 0, 781, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.qBeginDate = QtWidgets.QDateEdit(self.layoutWidget)
        self.qBeginDate.setStyleSheet("QDateEdit{\n"
"    color: rgb(81, 81, 81);\n"
"    font: 57 16pt \"思源黑体 CN Normal\";\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.692, y1:0.926136,         x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,             182, 255));\n"
"}\n"
"QDateEdit:hover{\n"
"    border: 1px solid #e4e4e4;\n"
"}\n"
"QDateEdit::drop-down{\n"
"    padding-right:10px;\n"
"    width: 10px;\n"
"    image: url(:/images/arrow_down.png);\n"
"}\n"
"QCalendarWidget{\n"
"    font: 14pt \"思源黑体 CN Normal\";\n"
"}\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,stop: 0 #313947, stop: 1 #34375E);    \n"
"}\n"
"QCalendarWidget QToolButton{\n"
"    color: white;background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button{\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    width:20px;\n"
"    image: url(:/images/arrow_up.png);\n"
"}\n"
"QCalendarWidget QSpinBox::down-button{\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    width:20px;\n"
"    image: url(:/images/arrow_down.png);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button:hover{\n"
"    background-color: rgba(215, 218, 223, 100);\n"
"}\n"
"QCalendarWidget QSpinBox::down-button:hover{\n"
"    background-color: rgba(215, 218, 223, 100);\n"
"}")
        self.qBeginDate.setCalendarPopup(True)
        self.qBeginDate.setObjectName("qBeginDate")
        self.horizontalLayout.addWidget(self.qBeginDate)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setHorizontalSpacing(10)
        self.formLayout_5.setVerticalSpacing(0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.qEndDate = QtWidgets.QDateEdit(self.layoutWidget)
        self.qEndDate.setAutoFillBackground(False)
        self.qEndDate.setStyleSheet("QDateEdit{\n"
"    color: rgb(81, 81, 81);\n"
"    font: 57 16pt \"思源黑体 CN Normal\";\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    padding-left:10px;\n"
"    padding-right:10px;\n"
"    background-color:qlineargradient(spread:pad, x1:0.692, y1:0.926136,         x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,             182, 255));\n"
"}\n"
"QDateEdit:hover{\n"
"    border: 1px solid #e4e4e4;\n"
"}\n"
"QDateEdit::drop-down{\n"
"    padding-right:10px;\n"
"    width: 10px;\n"
"    image: url(:/images/arrow_down.png);\n"
"}\n"
"QCalendarWidget{\n"
"    font: 14pt \"思源黑体 CN Normal\";\n"
"}\n"
"QCalendarWidget QWidget#qt_calendar_navigationbar{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 0,stop: 0 #313947, stop: 1 #34375E);    \n"
"}\n"
"QCalendarWidget QToolButton{\n"
"    color: white;background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button{\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    width:20px;\n"
"    image: url(:/images/arrow_up.png);\n"
"}\n"
"QCalendarWidget QSpinBox::down-button{\n"
"    background-color: rgba(255, 255, 255, 100);\n"
"    width:20px;\n"
"    image: url(:/images/arrow_down.png);\n"
"}\n"
"QCalendarWidget QSpinBox::up-button:hover{\n"
"    background-color: rgba(215, 218, 223, 100);\n"
"}\n"
"QCalendarWidget QSpinBox::down-button:hover{\n"
"    background-color: rgba(215, 218, 223, 100);\n"
"}")
        self.qEndDate.setCalendarPopup(True)
        self.qEndDate.setObjectName("qEndDate")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.qEndDate)
        self.horizontalLayout_3.addLayout(self.formLayout_5)
        self.gridLayout_22.addWidget(self.frame_17, 1, 0, 1, 1)
        self.gridLayout_19.addWidget(self.frame_14, 0, 0, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_15.sizePolicy().hasHeightForWidth())
        self.frame_15.setSizePolicy(sizePolicy)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setGeometry(QtCore.QRect(0, 200, 801, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_16.sizePolicy().hasHeightForWidth())
        self.frame_16.setSizePolicy(sizePolicy)
        self.frame_16.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_16.setStyleSheet("QPushButton{\n"
"    max-height:80px;\n"
"    min-height:80px;\n"
"    min-width:90px;\n"
"    max-width:90px;\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(243, 243, 243, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(144, 147, 153, 255), stop:1 rgba(94, 94, 94, 255));\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setHorizontalSpacing(10)
        self.gridLayout_21.setVerticalSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.qExportBtn = QtWidgets.QPushButton(self.frame_16)
        self.qExportBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qExportBtn.setStyleSheet("")
        self.qExportBtn.setObjectName("qExportBtn")
        self.gridLayout_21.addWidget(self.qExportBtn, 1, 3, 1, 1)
        self.qClearBtn = QtWidgets.QPushButton(self.frame_16)
        self.qClearBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qClearBtn.setObjectName("qClearBtn")
        self.gridLayout_21.addWidget(self.qClearBtn, 1, 4, 1, 1)
        self.qQueryBtn = QtWidgets.QPushButton(self.frame_16)
        self.qQueryBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qQueryBtn.setObjectName("qQueryBtn")
        self.gridLayout_21.addWidget(self.qQueryBtn, 1, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(15, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem3, 1, 7, 1, 1)
        self.qBackBtn = QtWidgets.QPushButton(self.frame_16)
        self.qBackBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.qBackBtn.setStyleSheet("QPushButton{\n"
"    font: 87 16pt \"思源黑体 CN Heavy\";\n"
"    color: #909399;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(243, 243, 243, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 135, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #fff;\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(255, 76, 76, 255), stop:1 rgba(108, 108, 108, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0.892, x2:1, y2:1, stop:0 rgba(144, 147, 153, 255), stop:1 rgba(94, 94, 94, 255));\n"
"}")
        self.qBackBtn.setText("")
        self.qBackBtn.setIcon(icon)
        self.qBackBtn.setIconSize(QtCore.QSize(48, 48))
        self.qBackBtn.setObjectName("qBackBtn")
        self.gridLayout_21.addWidget(self.qBackBtn, 1, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_15)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 801, 201))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qTableWidget_1 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.qTableWidget_1.setMaximumSize(QtCore.QSize(16777215, 270))
        self.qTableWidget_1.setStyleSheet("/*QTableView 左上角样式*/\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: 5px solid rgba(241, 241, 241, 255);\n"
"    background-color:rgba(241, 241, 241, 255);\n"
" }\n"
"QTableWidget {\n"
"    font-size:12pt;\n"
"    color: rgb(81, 81, 81);/*表格内文字颜色*/\n"
"    gridline-color: #e4e4e4;/*表格内框颜色*/\n"
"    background-color: #fff; /*表格内背景色*/\n"
"}\n"
"QHeaderView {\n"
"    color:rgb(81, 81, 81);\n"
"    font: 75 14pt \"思源黑体 CN Bold\";\n"
"    background-color:rgba(241, 241, 241, 255);\n"
"    min-height:40px;\n"
"}\n"
"QHeaderView::section {\n"
"    color:rgb(81, 81, 81);\n"
"    background-color: qlineargradient(spread:pad, x1:0.692, y1:0.926136,x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,182, 255));\n"
"    border: 1px solid #e4e4e4;\n"
"}\n"
"QScrollBar::vertical{\n"
"    width:40px;\n"
"}")
        self.qTableWidget_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.qTableWidget_1.setObjectName("qTableWidget_1")
        self.qTableWidget_1.setColumnCount(2)
        self.qTableWidget_1.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_1.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.qTableWidget_1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.qTableWidget_1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_1.setItem(2, 0, item)
        self.qTableWidget_1.horizontalHeader().setDefaultSectionSize(200)
        self.qTableWidget_1.horizontalHeader().setStretchLastSection(True)
        self.qTableWidget_1.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.qTableWidget_1)
        self.qTableWidget_2 = QtWidgets.QTableWidget(self.layoutWidget1)
        self.qTableWidget_2.setMaximumSize(QtCore.QSize(16777215, 270))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.qTableWidget_2.setFont(font)
        self.qTableWidget_2.setStyleSheet("/*QTableView 左上角样式*/\n"
"QTableWidget QTableCornerButton::section {\n"
"    border: 5px solid rgba(241, 241, 241, 255);\n"
"    background-color:rgba(241, 241, 241, 255);\n"
" }\n"
"QTableWidget {\n"
"    font-size:12pt;\n"
"    color: rgb(81, 81, 81);/*表格内文字颜色*/\n"
"    gridline-color: #e4e4e4;/*表格内框颜色*/\n"
"    background-color: #fff; /*表格内背景色*/\n"
"}\n"
"QHeaderView {\n"
"    color:rgb(81, 81, 81);\n"
"    font: 75 14pt \"思源黑体 CN Bold\";\n"
"    background-color:rgba(241, 241, 241, 255);\n"
"    min-height:40px;\n"
"}\n"
"QHeaderView::section {\n"
"    color:rgb(81, 81, 81);\n"
"    background-color: qlineargradient(spread:pad, x1:0.692, y1:0.926136,x2:0.692, y2:1, stop:0 rgba(241, 241, 241, 255), stop:1 rgba(182, 182,182, 255));\n"
"    border: 1px solid #e4e4e4;\n"
"}\n"
"QScrollBar::vertical{\n"
"    width:40px;\n"
"}")
        self.qTableWidget_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.qTableWidget_2.setObjectName("qTableWidget_2")
        self.qTableWidget_2.setColumnCount(2)
        self.qTableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.qTableWidget_2.setHorizontalHeaderItem(1, item)
        self.qTableWidget_2.horizontalHeader().setDefaultSectionSize(90)
        self.qTableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.qTableWidget_2.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.qTableWidget_2)
        self.gridLayout_19.addWidget(self.frame_15, 2, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.queryPage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.backBtn_2.clicked.connect(self.backBtn.click) # type: ignore
        self.qBackBtn.clicked.connect(self.backBtn.click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.queryBtn.setText(_translate("MainWindow", "查询"))
        self.testBtn.setText(_translate("MainWindow", "检测"))
        self.shutdownBtn.setText(_translate("MainWindow", "关机"))
        self.tempBtn.setText(_translate("MainWindow", "调试"))
        self.quitBtn.setText(_translate("MainWindow", "退出"))
        self.tempBtn_2.setText(_translate("MainWindow", "预热"))
        self.temp_downBtn_2.setText(_translate("MainWindow", "常温"))
        self.temp_upBtn.setText(_translate("MainWindow", "扩增"))
        self.temp_downBtn.setText(_translate("MainWindow", "测温"))
        self.stopBtn.setText(_translate("MainWindow", "急停"))
        self.ding_halfBtn.setText(_translate("MainWindow", "混合"))
        self.ding_halfBtn_2.setText(_translate("MainWindow", "层析\n"
"反应"))
        self.testBtn_2.setText(_translate("MainWindow", "检测"))
        self.captureImgBtn.setText(_translate("MainWindow", "抓图"))
        self.measureBtn.setText(_translate("MainWindow", "检测"))
        self.previewBtn.setText(_translate("MainWindow", "预览"))
        self.lamp_Btn.setText(_translate("MainWindow", "开始"))
        self.mClearBtn.setText(_translate("MainWindow", "终止"))
        self.numLineEdit.setPlaceholderText(_translate("MainWindow", "请输入检测编号"))
        item = self.resultTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.resultTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R(a.u)"))
        self.label_3.setText(_translate("MainWindow", "开始:"))
        self.label_9.setText(_translate("MainWindow", "结束:"))
        self.qExportBtn.setText(_translate("MainWindow", "导出"))
        self.qClearBtn.setText(_translate("MainWindow", "删除"))
        self.qQueryBtn.setText(_translate("MainWindow", "查询"))
        item = self.qTableWidget_1.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.qTableWidget_1.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.qTableWidget_1.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.qTableWidget_1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "时间"))
        item = self.qTableWidget_1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "编号"))
        __sortingEnabled = self.qTableWidget_1.isSortingEnabled()
        self.qTableWidget_1.setSortingEnabled(False)
        self.qTableWidget_1.setSortingEnabled(__sortingEnabled)
        item = self.qTableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.qTableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.qTableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.qTableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.qTableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "R(a.u)"))
import images_rc
